name: infixedu
description: A new Flutter application.

version: 1.0.3+4

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  shared_preferences: ^0.5.6
  permissions_plugin: ^1.1.4
  file_picker: 1.4.3+2
  fluttertoast: ^3.1.3
  path_provider: ^1.5.0
  dio: ^3.0.0
  file_utils: ^0.1.3
  flutter_calendar_carousel: ^1.4.10
  scoped_model: ^1.0.1
  flutter_cupertino_date_picker: ^1.0.12
  open_file: ^2.1.1
  flutter_launcher_icons: 0.7.3
  flutter_cupertino_localizations: ^1.0.1
  flutter_localizations:
    sdk: flutter
  uuid: ^2.0.0
  square_in_app_payments: ^1.3.0
  flutter_webview_plugin: ^0.3.10+1
  razorpay_flutter: ^1.1.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  image_path: images/launcher.png
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: popins
      fonts:
        - asset: fonts/poppins_medium.ttf
          weight: 100
        - asset: fonts/poppins_bold.ttf
          weight: 200
        - asset: fonts/poppins_light.ttf
          weight: 300
        - asset: fonts/poppins_regular.ttf
          weight: 400
        - asset: fonts/poppins_semibold.ttf
          weight: 500
  #      - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
